apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-web-demo
  labels:
    app: web-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-demo
  template:
    metadata:
      labels:
        app: web-demo
    spec:
      affinity:
        podAntiAffinity: # HA: Không cho 2 pod nằm trên cùng 1 node
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - web-demo
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources: # Resource Management
          limits:
            cpu: "200m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "64Mi"
        livenessProbe: # Health Check
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10